# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-fix-test',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/nbdev-fix-test',
                'lib_path': 'nbdev_fix_test'},
  'syms': {'nbdev_fix_test.core': {'nbdev_fix_test.core.foo': ('core.html#foo', 'nbdev_fix_test/core.py')}}}